### ISSUE TITLE
Add-on no longer auto-saves

### ISSUE THREAD

**Issue by xpseudonym** [dlech/AutoSaveDraftsFolders#6]
No longer auto-saves
I have auto-save set to every 5 mins in prefs
The last auto-save committed to my auto-save drafts local folder was 30.05.17...
It's now 04.06.17
I don't know when this first stopped - but, I noticed it when I lost a whole lot of work 30.05.17
T'bird version: 45.8.0
Running on Fedora 24

**Comment by dlech** [comment]
Only supporting TB 68 now

**Comment by xpseudonym** [comment]
Yeah, that was a while ago now - thanks.
