### ISSUE TITLE
Incompatible with Thunderbird v68.0b1

### ISSUE THREAD

**Issue by Grossdm** [dlech/AutoSaveDraftsFolders#7]
To enable the use of uBlock Origin, I migrated to the beta version of Thunderbird.
Wow, that broke every addon!

Thankfully, Enigmail has nightly builds which work with the Thunderbird beta.
Part of my GPG setup in Thunderbird is AutoSaveDraftsFolders.

Unfortunately, I did not find any beta/prerelease versions of ASDF.  In fact, it looks like you have not worked on it for some time.

Have you decided to stop maintaining it?
Do you have any suggestions?

Thank you.

**Comment by dlech** [comment]
It has been super-low priority since there are so few users. However, I do have a gmail account for work now, so that may motivate me a bit. Hopefully the changes to make it work are not too bad: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63.

**Comment by biva** [comment]
Great news, thanks @dlech 
Just for information, it's not compatible with TB68 either.
I'm available for testing :)

**Comment by dlech** [comment]
Keep an eye on #8. It won't work in TB 68.0, but will hopefully get it working in TB68.1.

**Comment by dlech** [comment]
TB 68.1 is out and this extension is working again.

Install manually from: https://github.com/dlech/AutoSaveDraftsFolders/releases/tag/v1.0.0

Pending review at https://addons.thunderbird.net/en-US/thunderbird/addon/auto-save-drafts-folders/
